name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # Source: https://github.com/srvaroa/labeler
    # Using this instead of the GH labeler action as the former supports labeling based on LoC changed.
    # However, it doesn't work with regex pattern to ignore generated files (CRDs, docs, etc.) in diff.
    # An issue has been filed https://github.com/srvaroa/labeler/issues/33 to track this improvement.
    - uses: srvaroa/labeler@v0.9
      with:
        config_path: .github/configs/labeler.yml
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
