name: pr-labeler
on:
- pull_request_target

jobs:
  add-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # This action originates from https://github.com/srvaroa/labeler. We are
    # using this action instead of the GitHub labeler action as the former
    # supports adding labels based on the number of changed, lines-of-code.
    #
    # * GitHub labeler LoC support:
    #   https://github.com/actions/labeler/issues/486
    #
    - uses: srvaroa/labeler@v1.10.1
      with:
        config_path: .github/configs/labeler.yml
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
