name: pr-labeler
on:
  pull_request_target:
    types:
    - synchronize
    - opened
    - reopened
    - labeled
    - unlabeled

jobs:
  add-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # This action originates from https://github.com/srvaroa/labeler. We are
    # using this action instead of the GitHub labeler action as the former
    # supports adding labels based on the number of changed, lines-of-code.
    # However, while the GitHub labeler action supports excluding files, the
    # action we are using does not. It would be nice if the GitHub labeler
    # action supported LoC labeling or if this action supported exclusions.
    # There are issues filed for both:
    #
    # * GitHub labeler LoC support:
    #   https://github.com/actions/labeler/issues/486
    #
    # * srvaroa labeler action exclusion support:
    #   https://github.com/srvaroa/labeler/issues/33
    #
    # For now we will use the srvaroa labeler action to afford ourselves the
    # support for LoC-based labels. If/when GitHub supports LoC, we will switch
    # to that and ignore the following, generated content:
    #
    # - "*_generated.go"       # generated Go sources
    # - "config/crd/bases/.*"  # generated CRDs
    # - "docs/apis/v*.md"      # generated API documentation,
    #                          # ex. docs/apis/v1alpha1.md
    - uses: srvaroa/labeler@v0.9
      with:
        config_path: .github/configs/labeler.yml
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  check-labels:
    needs: add-labels
    strategy:
      matrix:
        # the types of tests that are expressed as labels, ex. for the test
        # type "e2e-fast", the labels would be testing-needed-e2e-fast and
        # testing-done-e2e-fast
        test-type:
        - e2e-fast
        - e2e-full
    runs-on: ubuntu-latest
    steps:
    - name: do-not-merge
      # the step will run if one of the labels is present and the corresponding
      # label indicating testing is done is not present, ex. the label
      # testing-needed-e2e-fast is present without also testing-done-e2e-fast
      if: |
        contains(github.event.*.labels.*.name, format('testing-needed-{0}', matrix.test-type)) &&
        !contains(github.event.*.labels.*.name, format('testing-done-{0}', matrix.test-type))
      run: |
        echo "Pull request is labeled as 'testing-needed-${{ matrix.test-type }}'"
        exit 1
