name: testing-needed

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - labeled
    - unlabeled

jobs:
  check-lines-of-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Compare diff
        id: compare-diff
        run: |
          loc=$(git diff --shortstat HEAD ${{ github.event.pull_request.base.sha}} | awk '{print $4+$6}')
          echo "Lines of change: $loc"
          echo "lines_of_change=$loc" >> $GITHUB_OUTPUT
      - name: Apply 'testing-needed-*' label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # TODO: Add testing-needed-e2e-full label once the pipeline supports running e2e-full tests.
          script: |
            if (${{ steps.compare-diff.outputs.lines_of_change > 100 }}) {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['testing-needed-e2e-fast']
              })
            } else {
              try {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'testing-needed-e2e-fast'
                })
              } catch (e) {
                if (e.status !== 404) {
                  throw e
                }
              }
            }

  fetch-label:
    runs-on: ubuntu-latest
    needs: check-lines-of-change
    outputs:
      label_names: ${{ steps.fetch-label.outputs.label_names }}
    steps:
      - name: Fetch label
        id: fetch-label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })
            const label_names = labels.data.map(label => label.name)
            core.info('Fetched label names: ' + label_names)
            core.setOutput('label_names', label_names)

  check-label:
    runs-on: ubuntu-latest
    needs: fetch-label
    strategy:
      matrix:
        # the types of tests that are expressed as labels, ex. for the test
        # type "e2e-fast", the labels would be testing-needed-e2e-fast and
        # testing-done-e2e-fast
        test-type:
        - e2e-fast
        - e2e-full
    steps:
    - name: do-not-merge
      env:
        LABEL_NAMES: ${{ needs.fetch-label.outputs.label_names }}
      # the step will run if one of the labels is present and the corresponding
      # label indicating testing is done is not present, ex. the label
      # testing-needed-e2e-fast is present without also testing-done-e2e-fast
      if: |
        contains(env.LABEL_NAMES, format('testing-needed-{0}', matrix.test-type)) &&
        !contains(env.LABEL_NAMES, format('testing-done-{0}', matrix.test-type))
      run: |
        echo "Pull request is labeled as 'testing-needed-${{ matrix.test-type }}'"
        exit 1
